version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-shalom
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shalom_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - shalom-network

volumes:
  mysql-data:

networks:
  shalom-network:
    driver: bridge
